# hnnggghhhh docker compose docker compose
version: '3.4'

services:

  wordpress:
    container_name: wordpress
    hostname: wordpress
    build:
      context: ./requirements/wordpress
      args:
        - TEST=TEST
    restart: on-failure
    networks:
      - epic

  nginx:
    container_name: nginx
    hostname: nginx
    ports:
      - "8080:80"
    build:
      context: ./requirements/nginx
    restart: on-failure
    networks:
      - epic

networks:
  epic:
    driver: bridge # isolated network between all containers