# hnnggghhhh docker compose docker compose
version: '3.4'

services:
  mariadb:
    container_name: mariadb
    hostname: mariadb
    restart: on-failure
    build:
      context: ./requirements/mariadb
    expose:
      - 3306
    networks:
      - epic

  wordpress:
    container_name: wordpress
    hostname: wordpress
    depends_on:
      - mariadb
    build:
      context: ./requirements/wordpress
      args:
        - TEST=TEST
    expose:
      - 9000
    restart: on-failure
    networks:
      - epic

  nginx:
    container_name: nginx
    hostname: nginx
    depends_on:
      - wordpress
    ports:
      - "8080:80"
    build:
      context: ./requirements/nginx
    restart: on-failure
    networks:
      - epic

networks:
  epic:
    driver: bridge # isolated network between all containers