FLUSH PRIVILEGES;

-- Create database
CREATE DATABASE IF NOT EXISTS $DB_NAME;
USE $DB_NAME;

-- Create db admin user
CREATE USER IF NOT EXISTS '$DB_ADMIN_NAME'@'%' IDENTIFIED BY '$DB_ADMIN_PASSWORD';
GRANT ALL PRIVILEGES ON $DB_NAME.* to '$DB_ADMIN_NAME'@'%';
FLUSH PRIVILEGES;
