FROM debian:bookworm

# the wordpress version to install. I'm calling it
# MY_WORDPRESS_VERSION because idk if WORDPRESS_VERSION
# is a wordpress thing I cannot touch
ENV MY_WORDPRESS_VERSION="6.2.2"

#RUN echo $MY_WORDPRESS_VERSION
#RUN apt-get update && apt-get upgrade -y
#RUN apt-get install -y wget php8.2-fpm php8.2-mysql tar

WORKDIR /tmp

# download wordpress
#RUN wget https://wordpress.org/wordpress-$MY_WORDPRESS_VERSION.tar.gz

# extract wordpress
#RUN tar -xzvf wordpress-$MY_WORDPRESS_VERSION.tar.gz



CMD echo hi && sleep 99d